### ISSUE TITLE
Improved terminal output for scans

### ISSUE THREAD

**Issue by skalbfleisch** [NSLS-II/ophyd#102]
The current terminal output of scans in ophyd is not very useful for users. A formatted output of the motor positions and the read detectors would be helpful.

**Comment by gjwillms** [comment]
For additional information, see issue #74 and *shamelessly plugging own PR* pull request #87.  We've been using that branch at SRX for the last couple of weeks.  Maybe you could drop by and have a look to see if it's similar to what you're asking for.

**Comment by tacaswell** [comment]
The code from #87 has been merged in #108 / #103
