### ISSUE TITLE
Add first-class 'time' scan

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/ophyd#115]
Equivalent to

```python
def tscan(steps, delay):
    for s in range(steps):
        ct()
        time.sleep(delay)
```

**Comment by stuwilkins** [comment]
What about just having a dummy positioner that counts? That would be much more within our eco-system.

S

**Comment by tacaswell** [comment]
Why is adding a dummy positioner more natural? And that does not deal with
the delay time nicely with out abusing settle time.

**Comment by tacaswell** [comment]
Taken care of by bluesky in `Count`
