### ISSUE TITLE
Strings as waveforms

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#125]
We don't currently support strings. There are two places I'm aware of that will need to be addressed:

* ~~in runengine.py's `_build_data_keys` (formerly `_get_info`), where strings are currently interpreted as numpy arrays, marked as `'array'` type and labeled with a `shape`~~
* in pyepics/pyepics#22 which has a known issue with Python 3.4 where all strings get a `b` tacked onto the end (a cheap workaround is obvious...haha...but we should probably fix it the right way)

**Comment by tacaswell** [comment]
This issue is a place holder to make sure pyepics/pyepics#22 is rebased and merged.

**Comment by klauer** [comment]
Fixed upstream.
