### ISSUE TITLE
metadatastore master breaks all the things (or maybe, one logging statement)

### ISSUE THREAD

**Issue by ericdill** [NSLS-II/ophyd#132]
For example: `https://github.com/NSLS-II/ophyd/blob/master/ophyd/runengine/runengine.py#L333` will be broken because `https://github.com/NSLS-II/ophyd/blob/master/ophyd/runengine/runengine.py#L326` returns a uid!

**Comment by danielballan** [comment]
Good catch. That particular line is not exercised until users increase log verbosity, so I missed it. Any others I missed? I quick search for `.uid` turned up nothing else.

**Comment by danielballan** [comment]
A more thorough look through the vicinity of the `insert_*` logic also turned up nothing else. Let's take this for a test drive at CSX to be sure.
