### ISSUE TITLE
AD object that can take mulitple dark frames

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/ophyd#152]
The fastccd at CSX needs to be able to take multiple dark-frames (one at each gain setting).

The rough outline of what need to be done:

 - [ ] change the dark-frame logic to be gain-aware and take 3 images
 - [ ] change the last_dark_uid logic to keep track of a tuple instead
 - [ ] sort out with CSX what naming they want in the read dict
 - [ ] update read/describe so that they return all three dark-frame 

@stuwilkins

**Comment by klauer** [comment]
Multitrigger takes care of this stuff.
