### ISSUE TITLE
add ophyd object for top-off monitor

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/ophyd#153]
@stuwilkins has written an IOC which captures the timestamps of top off into a buffer.  The idea is to use this as a flyer in BS.  The behavior would be:
- [ ] on kick off reset and enable the IOC 
- [ ] return a status object that always returns that it is ready to be read
- [ ] on collect, disable and read the buffer
- [ ] each top-off event goes into MDS as a single event 

@stuwilkins Can you paste the PV details in this issue?

**Comment by stuwilkins** [comment]
Hi Tom, 

The IOC can be found here:

https://github.com/NSLS-II-CSX/timestamp

Very simple. 

$(Sys)$(Dev)Sw-Sel should be set to 0 to idle, 1 to start recording timestamps and 2 to clear the buffer. Note after setting 2 the user should set zero to idle. 

The buffer of timestamps can be read with $(Sys)$(Dev)Val:Time-Wfrm

$(Sys)$(Dev)Sts-Sts gives some status information (Such as recording, buffer full etc.)

HTH.
