### ISSUE TITLE
ENH: integrate diffractometer calculation library, hkl

### ISSUE THREAD

**Issue by klauer** [NSLS-II/ophyd#16]
git [repository](http://repo.or.cz/w/hkl.git): [next branch](http://repo.or.cz/w/hkl.git/shortlog/refs/heads/next)

Need some experts' opinions on how this should be implemented properly.

**Comment by tacaswell** [comment]
https://github.com/NSLS-II/wishlist/issues/12

https://github.com/NSLS-II/wishlist/issues/12
