### ISSUE TITLE
Implement settle_time on EpicsMotor

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#169]
I added `settle_time` to the signatures of EpicsMotor and PVPositioenr here: https://github.com/klauer/ophyd/commit/cabbda19abd811f6b6c78465b2cd80bba1a8db4c

...but I never added a sleep to Epics Motor

TODO after the refactor

**Comment by klauer** [comment]
Huh! Look at this - `settle_time` with no actual implementation... interesting... 

Closed by #283
