### ISSUE TITLE
ENH: channel access server for scan control, status information, etc.

### ISSUE THREAD

**Issue by klauer** [NSLS-II/ophyd#17]
Using [pcaspy](https://code.google.com/p/pcaspy/).

Need to come up with a clean interface to the above.

Moved channel access server functionality to a separate package (https://github.com/klauer/pypvserver).

**Comment by klauer** [comment]
With `CasPV`s (channel access server PVs) and `CasFunction` decorators (which can expose Python functions over the CA server), we can easily implement this now.

The question that remains is -- how do we want it to look on the EPICS-side? @dchabot @stuwilkins @arkilic

**Comment by tacaswell** [comment]
Closing this as development is moved to https://github.com/NSLS-II/pypvserver and there has been no motion on this is almost 2 years.
