### ISSUE TITLE
Expose ArrayData in area detector objects

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#182]
It won't normally be included in `read_attrs` or `configuration_attrs`, but it would be convenient to be able to access the data for debugging purposes. It's a little tricky to fit `image1:ArrayData` into the existing class hierarchy, so we'll wait for @klauer.

**Comment by klauer** [comment]
What do you mean by 'be able to access the data'? At what point?

I believe `ArrayData` itself is already available, assuming you create the image plugin component on your detector (ref: [ArrayData](https://github.com/NSLS-II/ophyd/blob/master/ophyd/controls/areadetector/plugins.py#L141))

**Comment by danielballan** [comment]
By "access the data" I just mean `det.image1.array_data`. I don't think that attribute is currently implemented, but I could be wrong.

**Comment by klauer** [comment]
In that case, check my reference above - it exists and should (hopefully) be working.

**Comment by danielballan** [comment]
The source of confusion here was that area detector's don't have an image plugin by default. That has to be specified in a custom subclass (probably in the beamline's IPython profile).
