### ISSUE TITLE
Save all motor positions to the head section of a scan file before the scan starts 

### ISSUE THREAD

**Issue by hanfeiyan** [NSLS-II/ophyd#187]
Can we automatically save the output of "wh_pos(all)" into the head section of a scan file before the scan starts? This is a very desired feature which allows us to find out the state of the instrument for any scans.

**Comment by tacaswell** [comment]
This probably should be reported against bluesky, not ophyd, but yes.

The plan is to also add an easy way to monitor a motor during the scan in case of drift and what not.

**Comment by tacaswell** [comment]
attn @klauer @danielballan

**Comment by danielballan** [comment]
Right. We already do some of this -- for example, we record the original
position of a motor in a dscan -- and now it should be easy to extend this
to capture anything the user desires.
