### ISSUE TITLE
Naming suggestion: OphydDevice -> Device

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#190]
It is currently `ophyd.device.OphydDevice`. I think `ophyd.device.Device` is sufficient. Only worth doing this if we do it before we begin to deploy.

**Comment by tacaswell** [comment]
Might even be worth using importing to flatten the name space so we get `from ophyd import Device as OD`

**Comment by klauer** [comment]
I'm OK with this. `sed` away, @danielballan.
