### ISSUE TITLE
Add additional EpicsMotor components

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#196]
e.g., offset

**Comment by danielballan** [comment]
So did we tentatively decide that we will *not* expose this unless there is demand for it?

**Comment by klauer** [comment]
All that we discussed, with the exception of jog should be exposed. I think @hhslepicka is going to elaborate in another issue.

**Comment by hhslepicka** [comment]
Yes, I just did it! Issue #273 !
