### ISSUE TITLE
Device inheritance

### ISSUE THREAD

**Issue by klauer** [NSLS-II/ophyd#201]
In its current state, `Device` inheritance breaks `_sig_attrs` (and as @danielballan found, the trigger signal on a subclassed device).
Additionally, the current code puts signals from bases after those in the top-level class (which is reversed).

To do list:
* fix `_sig_attrs`
* ensure `signal_names` and `_sig_attr` order is correct!
* test these more thoroughly

The original changes from my commit here should fix both of the above, I believe:
https://github.com/danielballan/ophyd/commit/bf037c9b8477cb679ba023582394dd8fc2d8e972

**Comment by tacaswell** [comment]
Yup, I am convinced that @klauer is right and I was wrong.
