### ISSUE TITLE
Signals should implement read_configuration

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#202]
Discovered while trying to add `em.channels.chan22` as a detector. It implements `read` and `describe`; it should also implement `read_configuration` and `describe_configuration` so it can be used by bluesky.

**Comment by klauer** [comment]
When would we ever want `read_configuration` on a simple thing like a signal? Isn't this something bluesky should consider optional?

**Comment by danielballan** [comment]
If you don't think it's ever useful on a signal, then I'm happy to make it optional. But would it be useful to eventually capture things like limits in signal's configuration?

**Comment by klauer** [comment]
Good point. @dchabot had mentioned grabbing all that sort of information when pyepics successfully connected.

**Comment by danielballan** [comment]
In that case, see #203 :- )
