### ISSUE TITLE
Documentation Wish List

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#222]
* in positioners move the positioner entry above the pseudo pos docs so it is adjacent to the example -- but this should wait until positioner API stabilizes anyway
* Signal needs mention that it can be used to inject python-only stuff into Devices
* many plugins missing from inheritance diagram
* `Device.set` isn't showing up in autogen docs because it is not actually defined on the base class. Should we define a stub? We have one for `Device.stop`.

**Comment by klauer** [comment]
This is all taken care of, minus some diagrams
