### ISSUE TITLE
Conclusions from preliminary discussion about positioners

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#230]
- [ ] PVPositioner -> something with a word like "Template" in it
- [ ] PseudoPositioner -> something with a word like "Template" in it

- [x] Refactor `move` in Positioner to express a "synchronous" move in terms of a "async" move, merely watching the status object.

- [x] Add docstrings to PseudoPositioner and more docstring to Positioner.

- [x] Remove "soft positioner" args, attributes, and assumptions from Positioner base class.

- [ ] Add an `actuate` method to Positioner and make it the ultimate source of both `set` and `actuate`. Obviously need to add this Msg to bluesky plans.

- [ ] Ensure the following:
* get and put -- low level, comprehensive
* Positioners set(*args, **kwargs), actuate() -- pick apart setting the set point and moving to the set point
* All devices trigger() and read() -- analogue to set and actuate. Trigger has nothing to do with moving, setting.
* Maybe `move` is refactored as set + actuate (+ wait for status to complete) to maintain current actual behavior

**Comment by klauer** [comment]
Revisit naming of `Template`s - no one was happy about `PVPositionerTemplate` `PVPositionerPCTemplate`. Will leave for next refactor phase.

**Comment by tacaswell** [comment]
Closing this as no longer useful.
