### ISSUE TITLE
Problem accessing scan images

### ISSUE THREAD

**Issue by vivekthampy** [NSLS-II/ophyd#260]
Trying to retrieve images as below: 

ims = get_images(db['e54e9e'], 'fccd_image')

gives the error:

OSError: Unable to open file (Unable to open file: name = '/gpfs/xf23id/xf23id1/fccd_data/2016/02/07/d8710b44-8f0d-498a-b0d8_-000001.h5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

The h5 file in the GPFS drive is stored as "d8710b44-8f0d-498a-b0d8_-000000.h5", and not "d8710b44-8f0d-498a-b0d8_-000001.h5".

**Comment by tacaswell** [comment]
@stuwilkins Looks like that race condition is back in the stage.

**Comment by klauer** [comment]
Is this resolved?

**Comment by klauer** [comment]
Closing as this is not strictly an ophyd issue. Please re-open in NSLS-II/bug-reports if it still persists.
