### ISSUE TITLE
Positioner/EpicsMotor Additions

### ISSUE THREAD

**Issue by hhslepicka** [NSLS-II/ophyd#273]
@danielballan, @dchabot, @klauer 
Per discussed on the meeting on Feb, 17th regarding the EpicsMotor we decided that Positioner/EpicsMotor should implement the following:

- [ ] homing
- [ ] calibration (exists in commands.py?)
- [ ] limit switch stat (+ exception raising + status object stuff)
- [ ] velocity
- [ ] acceleration
- anything else?

**Comment by danielballan** [comment]
Issue #196 reminded me that I am interested in storing `offset` (forgive me if I'm forgetting the proper EPICS name). But I don't think we need to store the raw value per event, just the offset in configuration. Would that be OK with everyone?

**Comment by klauer** [comment]
@danielballan :+1: for adding `offset` to the list for configuration attrs.

**Comment by hhslepicka** [comment]
@danielballan :+1: for to ```offset``` too.

**Comment by hhslepicka** [comment]
Almost there! :8ball:
