### ISSUE TITLE
`mov` does not always update with final motor position

### ISSUE THREAD

**Issue by tacaswell** [NSLS-II/ophyd#288]
It looks like there is just some delay between when the motors report that they are done (the status objects are flipped) and all of the new positions have propagated through epics/ophyd.

@cmazzoli reports the motor really is at the correct position so this is cosmetic.

Moved from https://github.com/NSLS-II/wishlist/issues/107

**Comment by klauer** [comment]
Probably would be easiest just to temporarily increase `settle_time` for all `mov`ed positioners and reset it after.

**Comment by klauer** [comment]
I can't come up with an intelligent and generic way to do this, beside for adding arbitrary delays or making some assumptions about the positioner deadband. Without deadband info, what is the "final position" after all?

**Comment by tacaswell** [comment]
`mov` will be removed via #410, closing.
