### ISSUE TITLE
BUG: Areadetector "trigger" timeout is shorter than long exposure. 

### ISSUE THREAD

**Issue by stuwilkins** [NSLS-II/ophyd#38]
When doing long exposure "put complete" times out before end of frame (when counting 120s)
Should this be configurable?

**Comment by klauer** [comment]
As of 5c7007ad34cee012896fbda3d68d9bd0cdf6ac74, timeout is now exposed with `EpicsSignal.put(1, timeout=120, **kwargs)`, where kwargs are passed to `epics.PV.put`.
