### ISSUE TITLE
Data storage server down

### ISSUE THREAD

**Issue by xiaojinghuang** [NSLS-II/ophyd#382]
This is a urgent issue. The GPFS server is down. Bluesky scan engine couldn't access to storage directory, we cannot run any scan now.

**Comment by tacaswell** [comment]
Can you access the GPFS server via any other method on the workstation?  Can you IOCs see the GPFS?

My guess is not as nothing at the python layer knows about GPFS, it is simply a path in the file system.  I also do not think that the RE directly writes to the GPFS, the detector IOCs should be doing that them selves.

You should contact someone from Rob's group about this.

**Comment by cowanml** [comment]
Petkus is aware of the problem and is working on it.
-matt

**Comment by xiaojinghuang** [comment]
The server is back online now. Thanks a lot.
