### ISSUE TITLE
Remove commands.py

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#410]
See NSLS-II/bluesky#711

**Comment by danielballan** [comment]
Per in-person conversation with @stuwilkins, the original author of many of the features in commands.py, we agree that the olog-related convenience functions make more sense in a separate package, like a package of magics. NSLS-II is the only member of the incipient "ophyd dev community" that uses olog, so it doesn't make much sense to maintain it and test it in this package.

**Comment by stuartcampbell** [comment]
Makes sense
