### ISSUE TITLE
What happens is position is a vector.

### ISSUE THREAD

**Issue by stuartcampbell** [NSLS-II/ophyd#424]
For cases like the Tardis, where the motor position is a hkl vector - i.e. tuple.  Are we consistent about how we deal with the positions.

**Comment by tacaswell** [comment]
Coupled to https://github.com/NSLS-II/bluesky/issues/753

The semantics on `set` are that the input is what ever makes for that object.  Scalar floats for motors, enum strings for gate valves, and tuples for pseudo-positioners.

**Comment by tacaswell** [comment]
closed by NSLS-II/bluesky#873 , #462 , #461
