### ISSUE TITLE
Make hints ubiquitious

### ISSUE THREAD

**Issue by teddyrendahl** [NSLS-II/ophyd#487]
## Motivation
Since the `hints` feature looks like it is here to stay, I would like to add an empty implementation to `ophyd.Device`.  Then subclasses of Device would only need to fill a `_hints` class attribute instead of rewriting boilerplate property code. 

## Implementation
It looks like the standard structure of the hints is:
```python
def hints(self):
      return {'fields': [...]}
```
I think that the default can be an empty dictionary if the subclass does not reimplement `_hints`. This way you can check with just `if device.hints`, but I do see the benefit of defining the structure in the base implementation so it would look something like this:
```python
_hints = {'fields' : list()}
```
Just curious, is there anything else we use in the `hints` dictionary besides "fields"? 

## Implications
Any code that doesn't check for an empty dictionary explicitly but calls `hasattr(device, 'hints')` might run into issues.

**Comment by danielballan** [comment]
I just want to link this to #429.
