### ISSUE TITLE
Add hints to Device

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/ophyd#502]
@danielballan @mrakitin 

> Long-term fix: move `hints` into the `Device` class so that this doesn’t keep happening, as we discussed yesterday at ISR, with a property, a setter, and a class attribute `_default_hints`. Short-term fix: copy the pattern from ISR.

Current fix at ISR is [here](https://github.com/NSLS-II-ISR/isr_profiles/blob/master/profile_collection/startup/20-area-detectors.py#L105). This should be eventually moved to `Device` class
  
Sample usage that needs this feature (at SMI)
https://github.com/NSLS-II-SMI/ipython_ophyd/blob/master/profile_collection/startup/11-energy.py#L184

**Comment by teddyrendahl** [comment]
Absolutely! Linking #487 which seems similar. Currently `hints` require a lot of code duplication.

**Comment by mrakitin** [comment]
Fixing the link: https://github.com/NSLS-II-ISR/profile_collection/blob/master/startup/20-area-detectors.py#L105
