### ISSUE TITLE
Ophyd Docs Missing Info About setup_ophyd

### ISSUE THREAD

**Issue by ZLLentz** [NSLS-II/ophyd#518]
@klauer showed us the `MonitorDispatcher`, which seems to make our `ophyd` sessions with the `pyepics` control layer much more reliable, and explains a lot of race conditions we were scratching our heads over the last few months.

With a docstring like https://github.com/NSLS-II/ophyd/blob/master/ophyd/_pyepics_shim.py#L126-L130 that indicates it should always be called, I'm surprised that `ophyd.setup_ophyd` is not mentioned anywhere in the docs.

This setup routine should either be automatically run or included in the docs.

**Comment by danielballan** [comment]
Belatedly -- @ZLLentz Sorry to hear that you guys lost a bunch of time on this. You are right: it should be prominent in the documentation. I'm drafting a tutorial, and this is in it.

**Comment by tacaswell** [comment]
#520 also deprecates the need to do this, might be better to push on that?

**Comment by danielballan** [comment]
Oh, has your thinking changed on setup-on-init? I thought we avoided that intentionally. From a user's point of view it seems nice, but there's a risk of getting into a state where ophyd crashes Python on startup.

**Comment by tacaswell** [comment]
I think it is on ophyd to make sure setup is safe!  I think the historical issues were from the imports from libca not being sufficiently wrapped in try-except.

**Comment by klauer** [comment]
Right - the `setup()`-on-import functionality was removed at your request.

**Comment by danielballan** [comment]
> I think the historical issues were from the imports from libca not being sufficiently wrapped in try-except.

I see. Seems like that fine with @klauer and it's fine with me, just wanted to understand what changed.

**Comment by tacaswell** [comment]
@klauer In an case I have changed my mind and decided you were correct to begin with.
