### ISSUE TITLE
Individual Device Logging

### ISSUE THREAD

**Issue by teddyrendahl** [NSLS-II/ophyd#525]
## Description
Putting a proposal out there for attaching individual loggers to Ophyd devices. This allows you to track all the log messages emitted by an individual instantiation of a device. In fact, if you are clever about naming the loggers with their parent names you can log messages all the way down to the signal level. This would be a huge help with debugging as you can watch a single device `DEBUG` mode during a scan without taking the full firehose of DEBUG logs.

This has precedent within the software stack as the `RunEngine` prints to its own `.log`

## Implementation
```python
class Device:
    def __init__(self, prefix, * , **kwargs):
        super().__init__(prefix, **kwargs)
        if self.parent:
               self.log = logging.getLogger(self.parent.log.name + '.' + self.name)
         else:
               self.log = logging.getLogger(self.__class__.__module__ + '.' + self.name)

# Setup logging
m  = ophyd.EpicsMotor('Tst:Mtr:1', name='test_motor')
logging = getLogger('ophyd') # Still gets everything it did prior
m.log.addHandler(StreamHandler(level=logging.DEBUG)) # Debug from only my test_motor
```

## Consequences
On the top level this is harmless as `ophyd.Device` will have `.log`  that people can choose to use or not. However, as part of this I would like to go through the whole library and have devices write to their own logs. This will be a large PR that touches a lot of files that I wanted to get approval for ahead of time.

Original discussion https://github.com/pcdshub/pcdsdevices/issues/193

**Comment by tacaswell** [comment]
:+1:
