### ISSUE TITLE
Consider allowing multiple kinds specified as string.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#542]
Lifting @jrmlhermitte's suggestion from the line comments in #541:

> if provided in string format, I'd be more tempted to allow for a list of kinds:
`kind='normal,hinted'`

**Comment by tacaswell** [comment]
If we are going to go down this path, then it would make more sense to us `|` as the separator as that is how we will combine them under the hood.  But if we do that then we might want to also include the `&` operator as well, and then we are on our way to writing a mini-language.

**Comment by danielballan** [comment]
Given @tacaswell's point above I think this is not worth doing. Once people need a union/intersection whatever, it's time to just use Python instead of the string shortcut.

If anyone wants to continue debate, feel free to reopen the issue.
