### ISSUE TITLE
Allow disconnected devices to be instantiated

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II/ophyd#578]
We met a request from a BL staff to allow disconnected devices to be instantiated without raising. The idea is, for example, to avoid editing IPython collection profiles to exclude a detector from a pool of available detectors. After discussion with DAMA in NSLS-II Slack, we came up with an idea that such disconnected devices still can be silently instantiated, but when they are attempted to be staged/triggered, the attempt will fail with a raised error (this tripwire will help to avoid situations of collecting overnight data without a camera).

It is open for discussion.

**Comment by tacaswell** [comment]
Not allowing this was a conscious design choice.  We figured it was better to know if you device was off line (or you typed the PV wrong) as soon as possible.  It is probably worth re-addressing this choice in light of the above discussion and the impending GUI future.

The minimal change would be to make Component lazy by default, however that seems to produce race conditions when trying to use some complex devices (not clear why or where, but things go sideways badly).

**Comment by mrakitin** [comment]
Thanks for your feedback, @tacaswell! I thought it may be handy to have something like that in beamline profiles to work-around the situation with frequently changed equipment:
```py
try:
    det = DetectorClass(...)
except:
    det = None  # or NotImplemented
```

This way the profile will load fine, but it won't be possible to trigger the `det` detector.

**Comment by danielballan** [comment]
But then _every_ place that you use `det` you have to `if det is None` checks. Very much against that.

**Comment by ZLLentz** [comment]
We do something like this at SLAC with the try/except cascade. It creates the problems that Dan is talking about but our scientists much prefer the session get started with "something" than raising an exception and quitting. We wrap it with a context manager so that we only need one line and so that there is a clear ERROR log message with the failed device (bold red in our terminal):

https://github.com/pcdshub/hutch-python/blob/5e3aa362af93bde853eabe6d3417b1058dec4946/hutch_python/utils.py#L24-L53

**Comment by mrakitin** [comment]
@danielballan, fair point.

**Comment by tacaswell** [comment]
You could also do

```python
try:
    det = DectorKlass(...)
    sd.baseline.append(det)
except ConnectionError:
    pass
```

so it just is not there if it can not connect.

A down side of these approaches is if the device becomes available again later you have to restart the profile to get it.

I suspect the best path forward is sorting out how to make everything lazy by default and then explicitly checking connection on critical devices (ex refuse to start if we can not read the ring current?).

**Comment by klauer** [comment]
This is now resolved for devices included with ophyd, but beamline configurations that call `get/put/set` in `__init__` will need to be modified.  They will need to use connection callback hooks as in the updated `EpicsMotor` and AreaDetector `PluginBase`.
