### ISSUE TITLE
AreaDetector Does not Traverse Entire Tree

### ISSUE THREAD

**Issue by teddyrendahl** [NSLS-II/ophyd#635]
`AreaDetector` assumes that all plugins are the direct children of `ADBase`. This prevents grouping plugins like

```python
class CommonPlugins(Device):
        stats1 = Cpt(...)
        stats2 = Cpt(...)
         ....

class CommonDetector(ADBase):
      common_plugins = Cpt(CommonPlugins, ...)
```

https://github.com/NSLS-II/ophyd/blob/dd6a3a0335c7e9d6fe6fc0beb121977cfe637aa7/ophyd/areadetector/base.py#L188

**Comment by tacaswell** [comment]
attn @klauer

**Comment by klauer** [comment]
Thanks @tacaswell - will be looking into this

**Comment by tacaswell** [comment]
We had related issues with something at HXN iirc...
