### ISSUE TITLE
Deprecate / remove EpicsSignal pv_kw init argument

### ISSUE THREAD

**Issue by klauer** [NSLS-II/ophyd#643]
The intent of `EpicsSignal` is to abstract away pyepic's `PV` interface. However, `pv_kw` in the EpicsSignal initializer get passed through to `epics.PV` breaks this abstraction and should be removed.

I don't think anyone is using this in the wild, but it would be wise to check.

Additionally, keyword arguments are passed through for `EpicsSignal.put` and `EpicsSignal.get`. While I suppose that ship has sailed as they are assuredly used, perhaps we can restrict the keyword arguments we support in those cases and remove `**kwargs`.

Thoughts? @danielballan @tacaswell @teddyrendahl @ZLLentz

**Comment by prjemian** [comment]
not used at APS

**Comment by ZLLentz** [comment]
I don't think this is used at SLAC. I thought I needed it once but I was incorrect. I agree with the intent of this issue, but we should also see if any of the features here could have use cases that we want to make explicit arguments.

**Comment by tacaswell** [comment]
Verified it is not using by any profile which are committed to git.
