### ISSUE TITLE
Put Stuart's directory-generating script into ophyd.utils

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#84]

**Comment by tacaswell** [comment]
and make it left-pad months/days with 0

**Comment by tacaswell** [comment]
This should be done via the create-directory flag in AD

attn #165

**Comment by tacaswell** [comment]
via @dchabot http://cars9.uchicago.edu/software/epics/NDPluginFile.html

**Comment by klauer** [comment]
It may still be preferable to do it in Python, as you can set the permissions/ownership/etc as required. I don't think that exists in the AD file plugin, does it?

**Comment by tacaswell** [comment]
The machine running blue sky may not be able to see the disks that ad is
writing to.

**Comment by klauer** [comment]
Is this how other beamlines are setup (purposefully)? All of our machines at the HXN have access to where data is being written.

**Comment by tacaswell** [comment]
see GPFS

**Comment by klauer** [comment]
@tacaswell is that a reply to me? I don't know how GPFS is being setup.

**Comment by danielballan** [comment]
Leaving this here -- will make a PR later:

```python
import os
import sys
import calendar

def makedirs(path):
    try:
        os.makedirs(path)
    except OSError:
        pass


def make_dir_tree(year):
    makedirs(str(year))
    for month in range(1, 13):
        print(month)
        makedirs(os.path.join(str(year), '%02d' % month))
        _, num_days = calendar.monthrange(year, month)
        for day in range(1, 1 + num_days):
            makedirs(os.path.join(str(year), '%02d' % month , '%02d' % day))


if __name__ == '__main__':
    year = int(sys.argv[1])
    make_dir_tree(year)
```
