### ISSUE TITLE
PVPositioner without 'done' PV breaks iteration.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#89]
A missive from the trenches at XPD with @dchabot:

With `PVPositioner` instances, if a done PV is not provided, there is problem with iterating through a trajectory. We have a workaround in this instance, but we must revisit.

**Comment by tacaswell** [comment]
@danielballan Is this still relevant?

**Comment by danielballan** [comment]
I don't understand PVPositioner internals well enough to say.
