### ISSUE TITLE
Compare results from ophyd and qxrd

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/ophyd#91]
Refer to:

 Scan ID : 126

Detector | Value
============================================================
em_ch1 [ 0.00915527]
em_ch2 [ 0.00944138]
em_ch3 [ 0.01058578]
em_ch4 [ 0.01058578]
pe1_acquire_period [ 5.]
pe1_acquire_time [ 0.2]
pe1_image_lightfield ['c9281f96-091c-4122-8860-d5af4a2ac887']
shctl1 [ 1.]

================================================================================

**Comment by tacaswell** [comment]
unclear what is going on here, closing unless @danielballan has some insight.
