### ISSUE TITLE
Timestamps, Processing and areaDetector

### ISSUE THREAD

**Issue by stuwilkins** [NSLS-II/ophyd#93]
Ok, putting this as an issue so that we can discuss look at it. Attn. @dchabot @gjwillms @tacaswell .

After some discussion with Mark Rivers and playing with the AD Driver for the FastCCD I have managed to work out the issue with timestamps, and blocking. So, Firstly if you need to use the stats plugins (for example) you need to set them to blocking $(P)$(R)BlockingCallbacks. This will ensure that the put complete doesn't come back until the stats have processed.

Now in areaDetector 2.0 there is support for the epics records having the detector timestamp by setting the "TSE" field of those records. I tested this with the fastCCD (I take the timestamp of the first packet arriving at the detector electronics) and it looks good, even at 100Hz. Also all stats plugins have the same timestamp.

Also, the new HDF5 file plugin stores this info (timestamps) in the HDF5 file.

The info is here:

[areaDetector timestamps](http://cars.uchicago.edu/software/epics/areaDetectorTimeStampSupport.html)

**Comment by gjwillms** [comment]
I don't see any downside to this.  From my point of view, this implements the intended behavior of the Stats plugin during a scan.  We don't have an immediate need for fast time-stamping, but it's great to have it in reserve.

**Comment by stuwilkins** [comment]
Ok then i will implement it @tacaswell what is the state of my poor add_detectors branch?


On Mar 27, 2015, at 8:05 AM, gjwillms <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see any downside to this. From my point of view, this implements the intended behavior of the Stats plugin during a scan. We don't have an immediate need for fast time-stamping, but it's great to have it in reserve.

**Comment by stuwilkins** [comment]
P.s. I agree 100% this is actually what ad should do why it is not default is not clear to me.

Also, I noticed that AD 2.2 has a much simplified roi/stats plugin which should be much better for our intended use.

Best wishes,
Stuart


On Mar 27, 2015, at 08:05, gjwillms <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see any downside to this. From my point of view, this implements the intended behavior of the Stats plugin during a scan. We don't have an immediate need for fast time-stamping, but it's great to have it in reserve.

**Comment by tacaswell** [comment]
This is currently working at CSX

attn #165
